[package]
name = "aura-example-render-femtovg"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
baseview = { workspace = true }
slint = { workspace = true }
lx-aura-baseview = { workspace = true, features = ["backend-femtovg"] }

[build-dependencies]
slint-build = { workspace = true }
