//! Minimal stereo gain — proves format wrappers + `PluginLogic` end-to-end.
//!
//! ```bash
//! cargo build -p smoke-gain --release --features clap
//! cargo run -p cargo-aura -- install --clap --release
//! # or copy target/release/smoke_gain.dll → …/CLAP/smoke-gain.clap
//! clap-validator validate path/to/smoke-gain.clap
//!
//! # VST3 (same PluginLogic editor via IPlugView):
//! cargo build -p smoke-gain --release --features vst3
//! cargo run -p cargo-aura -- install --vst3 --release
//! ```

use std::sync::Arc;

use aura::prelude::*;

slint::include_modules!();

// Generated by #[derive(Params)] — editor code never hardcodes raw IDs.
use GainParamsParamId as P;

// ---------------------------------------------------------------------------
// Params
// ---------------------------------------------------------------------------

#[derive(Params)]
pub struct GainParams {
    #[param(id = 1, name = "Gain", range = "linear(-24, 24)", default = 0.0, unit = "db")]
    pub gain: FloatParam,
}

// ---------------------------------------------------------------------------
// Plugin
// ---------------------------------------------------------------------------

pub struct SmokeGain;

pub struct DspState;

impl PluginLogic for SmokeGain {
    type Params = GainParams;
    type DspState = DspState;

    fn info() -> PluginInfo {
        let mut info = PluginInfo::new(
            "AURA Smoke Gain",
            "LX Audiolabs",
            env!("CARGO_PKG_VERSION"),
            "smoke-gain",
        );
        info.clap_id = "com.lx-audiolabs.aura.smoke-gain";
        // Stable once shipped — host sessions key off this string → TUID.
        info.vst3_id = "com.lx-audiolabs.aura.smoke-gain";
        info.category = PluginCategory::Effect;
        info
    }

    fn init(_params: &Self::Params, _sample_rate: f64) -> Self::DspState {
        DspState
    }

    fn reset(_state: &mut Self::DspState, _params: &Self::Params, _config: &AudioConfig) {}

    fn process(
        _state: &mut Self::DspState,
        params: &Self::Params,
        buffer: &mut AudioBuffer<'_, f32>,
        _context: &mut ProcessContext,
    ) -> ProcessStatus {
        let n = buffer.num_samples();
        #[allow(clippy::cast_possible_truncation)]
        let gain_db = params.gain.raw_target() as f32;
        let lin = 10.0f32.powf(gain_db / 20.0);

        let ch = buffer.num_outputs().min(buffer.num_inputs());
        for c in 0..ch {
            // Copy input → output with gain (handle possible aliasing by reading first).
            let input: Vec<f32> = buffer.input(c).to_vec();
            let out = buffer.output(c);
            for i in 0..n {
                out[i] = input[i] * lin;
            }
        }
        // Extra outs: silence
        for c in ch..buffer.num_outputs() {
            buffer.output(c).fill(0.0);
        }
        ProcessStatus::Continue
    }

    fn editor(_params: Arc<Self::Params>) -> Option<Box<dyn Editor>> {
        Some(
            aura_editor::AuraSlintEditor::new(
                (320, 220),
                |ctx| {
                    let ui = AppWindow::new().expect("slint component");
                    let params = ctx.params.clone();
                    ui.on_gain_changed(move |v| params.set_plain(P::Gain.id(), f64::from(v)));
                    ui
                },
                |ui, ctx| {
                    #[allow(clippy::cast_possible_truncation)]
                    let v = ctx.params.get_plain(P::Gain.id()).unwrap_or(0.0) as f32;
                    // Guard: don't fight an active drag with per-frame sync.
                    if (v - ui.get_gain()).abs() > 1.0e-4 {
                        ui.set_gain(v);
                    }
                },
            )
            .into_editor(),
        )
    }
}

#[cfg(feature = "clap")]
aura::export!(SmokeGain);

#[cfg(feature = "vst3")]
aura::export_vst3!(SmokeGain);
